name: Hardcore
version: 0.0.2
main: world.komq.hardcore.plugin.HardcorePlugin
api-version: 1.19
libraries:
 - io.github.monun:tap-core:4.8.0
 - io.github.monun:kommand-core:3.0.0
 - io.github.monun:heartbeat-coroutines:0.0.4